<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260304112452 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dni_cif VARCHAR(255) NOT NULL, nombre_completo VARCHAR(255) NOT NULL, email_contacto VARCHAR(255) NOT NULL, telefono_contacto VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contrato (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, estado VARCHAR(255) NOT NULL, fecha_alta DATE NOT NULL, cliente_id INT DEFAULT NULL, servicio_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_66696523DE734E51 ON contrato (cliente_id)');
        $this->addSql('CREATE INDEX IDX_6669652371CAA3E7 ON contrato (servicio_id)');
        $this->addSql('CREATE TABLE servicio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, tipo VARCHAR(255) NOT NULL, precio_mensual DOUBLE PRECISION NOT NULL, activa BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_66696523DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id)');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_6669652371CAA3E7 FOREIGN KEY (servicio_id) REFERENCES servicio (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contrato DROP CONSTRAINT FK_66696523DE734E51');
        $this->addSql('ALTER TABLE contrato DROP CONSTRAINT FK_6669652371CAA3E7');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE contrato');
        $this->addSql('DROP TABLE servicio');
    }
}
